### ISSUE TITLE
engine: provide database information

### ISSUE THREAD

**Issue by SUMUKHA-PK** [xqueries/xdb#75]
To facilitate the inspector, the engine must expose a function that can provide functions that provide the following data:
- all tables
  - name
  - number of rows
- all indices
  - not applicable right now
- all views
  - not applicable right now

database file size and information should go into `storage.DBFile` and its `storage.PageManager`

**Comment by tsatke** [comment]
Number of pages is `fileSize / page.Size`.

**Comment by tsatke** [comment]
Main idea is to add a method `(Engine).Info() Info`, which returns something like a
```go
type Info struct {
    FileSize int64
    Tables []string
    Indices []string
    Views []string
}
```
If for tables, indices and views, there is more than just the name that would make sense to return, instead of `[]strings`s, appropriate structs should be provided.

**Comment by SUMUKHA-PK** [comment]
Yep.

Tables can have whatever data you have available. Sizes? Cols? Rows?
Please add a provision for number of pages too?

@tsatke

**Comment by tsatke** [comment]
Size computation is not trivial for tables. Since we only need that information for the inspector, IMO the inspector should compute that.

Amount of rows would make sense, and should be pretty easy to compute. Adding to the scope of this issue.

Number of pages: ok. But it literalls would just be `engine.Info().FileSize / page.Size`.
